### ISSUE TITLE
Getting the Output Stream from JNI Call

### ISSUE THREAD

**Issue by cheeseng** [javaaiorg/stable-diffusion.java#1]
I wonder if it is possible for us to get the output log in streaming mode so that we can build interactive UI with it?

**Comment by javaaiorg** [comment]
Good idea, now you can use new version 1.0.3 to custom log output. 

// example: 
// import org.javaai.stablediffusion.api.Util;
Util.setSDLogCallback((level, file, line, log) -> {
	System.out.println(SDLogUtil.formatLog(level, file, line, log));
});

**Comment by cheeseng** [comment]
Great, I'll give it a try today!

**Comment by cheeseng** [comment]
It works well, thanks!
